targets:
  $default:
    builders:
      dart_json_mapper:
        generate_for:
          - lib/main/main_local.dart
          - lib/main/main_prod.dart
          - lib/main/main_mock_server.dart
          - lib/main/main_mock_json.dart
      reflectable:
        generate_for:
          - no/files
