// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_bloc_advance/test/presentation/screen/settings/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_bloc/flutter_bloc.dart' as _i4;
import 'package:flutter_bloc_advance/configuration/local_storage.dart' as _i5;
import 'package:flutter_bloc_advance/presentation/common_widgets/drawer/drawer_bloc/drawer_bloc.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDrawerState_0 extends _i1.SmartFake implements _i2.DrawerState {
  _FakeDrawerState_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [DrawerBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDrawerBloc extends _i1.Mock implements _i2.DrawerBloc {
  MockDrawerBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DrawerState get state =>
      (super.noSuchMethod(Invocation.getter(#state), returnValue: _FakeDrawerState_0(this, Invocation.getter(#state)))
          as _i2.DrawerState);

  @override
  _i3.Stream<_i2.DrawerState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream), returnValue: _i3.Stream<_i2.DrawerState>.empty())
          as _i3.Stream<_i2.DrawerState>);

  @override
  bool get isClosed => (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false) as bool);

  @override
  void add(_i2.DrawerEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]), returnValueForMissingStub: null);

  @override
  void onEvent(_i2.DrawerEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]), returnValueForMissingStub: null);

  @override
  void emit(_i2.DrawerState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]), returnValueForMissingStub: null);

  @override
  void on<E extends _i2.DrawerEvent>(
    _i4.EventHandler<E, _i2.DrawerState>? handler, {
    _i4.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i4.Transition<_i2.DrawerEvent, _i2.DrawerState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]), returnValueForMissingStub: null);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void onChange(_i4.Change<_i2.DrawerState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]), returnValueForMissingStub: null);

  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]), returnValueForMissingStub: null);

  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]), returnValueForMissingStub: null);
}

/// A class which mocks [AppLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalStorage extends _i1.Mock implements _i5.AppLocalStorage {
  MockAppLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setStorage(_i5.StorageType? type) =>
      super.noSuchMethod(Invocation.method(#setStorage, [type]), returnValueForMissingStub: null);

  @override
  _i3.Future<bool> save(String? key, dynamic value) =>
      (super.noSuchMethod(Invocation.method(#save, [key, value]), returnValue: _i3.Future<bool>.value(false))
          as _i3.Future<bool>);

  @override
  _i3.Future<dynamic> read(String? key) =>
      (super.noSuchMethod(Invocation.method(#read, [key]), returnValue: _i3.Future<dynamic>.value())
          as _i3.Future<dynamic>);

  @override
  _i3.Future<bool> remove(String? key) =>
      (super.noSuchMethod(Invocation.method(#remove, [key]), returnValue: _i3.Future<bool>.value(false))
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
